### ISSUE TITLE
process_data.py is not working

### ISSUE THREAD

**Issue by 613B** [Eighonet/parking-research#3]
Hi. 

First of all, I would like to thank you for your excellent research results.

Now I'm trying to create a custom dataset and execute binary classification on it.

I was able to get annotations using this project's annotators. So, I'm trying to get cropped images from `data_processer` as my next step. 

But the python script stopped here.

https://github.com/Eighonet/parking-research/blob/babb491db80dd39b6448d71e0544c09d282a5a41/data_processing/process_data.py#L164

It's trying to copy `splitted_images` from `int_markup_dir` that even though they don't exist.

How can I resolve this error?

And while I'm at it, I would like to ask, what is the difference between `splitted_images` and `patch_splitted`?

**Comment by slavajda02** [comment]
Hi.

I was looking at this yesterday and managed to fix it on my fork: https://github.com/slavajda02/parking-research-argon/blob/main/data_processing/process_data.py

I guess it is just a copy paste user error because there are no images in int_markup directory just jsons.

Splitted images directory is for intersection based models (object detection), and patch_splitted should be for patch based (image recognition), meaning that patch splitted should have only images of individual parking places cutted out from the original images.

The patch_crop function creates images of parking places, parch_ilm function sorts them into "busy" and "free" and splitter function should sort them into directories for training.

**Comment by 613B** [comment]
Hi, slavajda02-san.

I appreciate your solution (and some useful scripts such as inferecne notebook). I could resolve the problem.

I also understood difference between patch_splitted and splitted_images.

Thank you very much.
